### ISSUE TITLE
Implementation of NMS op for east detection

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#10935]

**Comment by wanghaoshuang** [comment]
east detection NMS建议接口设计：
``` 
proposal_nms_layer
input: rois_all: N x H x W x 9
param: top_k: top k rois of mini-batch
             score_thresh:
             iou_thresh:
output: rois_filtered: num_rois x 10 (batch_ind, x1, y1, ..., x4, y4, score)
```
