### ISSUE TITLE
paddle v2 api 支持分布式训练

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#1732]
### 现状
目前的v2 api只支持单机执行，而分布式任务依然使用以前的paddle train xxx的方式运行，启动trainer/ps 二进制，读取trainer_conf.py，然后通过data_provider读取数据进行训练。

### 需求
需要做一下升级，即在mpi node上通过python xxx.py的方式启动trainer进行训练，并且通过python的v2 api驱动整个训练进程。

### 需要做的点
1. 目前v2中的trainer只支持单机的gradient machine，所以现在需要做到能支持多机的gradient machine，接受合适的参数启动训练。
1. 修改之前的mpi提交程序receiver，切换成启动python版本的trainer和ps。
1. 之前的日志输出，也需要整理并兼容，方便调试。

**Comment by jacquesqiao** [comment]
https://github.com/PaddlePaddle/Paddle/issues/1680  和这个有一点关联

**Comment by typhoonzero** [comment]
初步的想法，求拍砖。
对于通用的MPI提交方式，可以由paddle API直接调用q_sub MPI client 提交任务。提交MPI集群的接口需要完成：
1. 寻找MPI client
2. 准备任务目录和配置文件
3. 提交
4. 获取日志

**Comment by Yancey1989** [comment]
我觉得会有两种路子：
1. 沿用receiver的思路（新reciver暂称为receiverv2），python的dist api调用receiverv2提交任务（维护只更新receiver，方便升级）
1. mpi client封装在paddle的dist api里（升级麻烦，需要用户升级paddle的package）

**Comment by jacquesqiao** [comment]
### paddle集群管理(mpi/k8s)方案前置工作
1.  调研清楚目前paddle receiver的工作机制并分享。 @gongweibao  @typhoonzero 
1.  python api支持分布式训练并分享。  @jacquesqiao
1. 调查清楚google cloud ml和其他类似服务的集群任务提交方式并分享。 @Yancey1989 @typhoonzero

**Comment by typhoonzero** [comment]
# 在k8s上启动一个测试用的MPI集群：

- 启动一个head Pod（使用了Deployment启动1个replica）:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mpi-header
  labels:
    app: mpi-header
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mpi-header
    spec:
      containers:
      - image: dispel4py/docker.openmpi
        name : mpi-header
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        ports:
        - containerPort: 22
```

- 启动一组mpi-node，可以在resource下面修改配额的大小：
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mpi-nodes
  labels:
    app: mpi-nodes
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: mpi-nodes
    spec:
      containers:
      - image: dispel4py/docker.openmpi
        name : mpi-header
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        ports:
        - containerPort: 22
```

- 使用ssh登录到head容器中：

    先找到head启动的IP地址：`kubectl get po -o wide`

```bash
git clone https://github.com/dispel4py/docker.openmpi.git
cd docker.openmpi
chmod 400 ssh/id_rsa.mpi
ssh -i ssh/id_rsa.mpi tutorial@[head的地址]
```

- 找到所有的mpi-node:
```bash
kubectl get po -a -o wide | grep mpi-nodes | awk '{print $6}' > machines
```
    然后把`machines`文件scp拷贝到head容器中

- 提交mpi任务：
```bash
mpiexec -hostfile machines -n 16 python helloworld.py 
```
