### ISSUE TITLE
xpu推理报错  [operator < bilinear_interp_v2 > error]

### ISSUE THREAD

**Issue by ZSharp7** [PaddlePaddle/Paddle#50294]
### 请提出你的问题 Please ask your question

# 环境
* OS: Ubuntu18.04
* Python: 3.7.13
* docker_images: registry.baidubce.com/device/paddle-xpu:ubuntu18-x86_64-gcc82
* XPU_Runtime: 4.0
* XPU_Driver: 4.0
* XPU: R200
* Paddle: 0.0.0
# 模型信息
* configs: ppseg -> rtformer_slim_ade20k_512x512_160k.xml
配置文件详细信息如下：
```yaml
_base_: '../_base_/ade20k.yml'

batch_size: 4 # total batch size:  4 * 4
iters: 160000

train_dataset:
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_dataset:
  transforms:
    - type: Resize
      target_size: [512, 512]
      keep_ratio: True
      size_divisor: 32
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  
export:
  transforms:
    - type: Resize
      target_size: [512, 512]
      keep_ratio: True
      size_divisor: 32
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

optimizer:
  _inherited_: False
  type: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.05

lr_scheduler:
  _inherited_: False
  type: PolynomialDecay
  learning_rate: 1.0e-4
  power: 1.
  end_lr: 1.0e-7
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4]

model:
  type: RTFormer
  base_channels: 32
  head_channels: 64
  drop_path_rate: 0.1
  cross_size: 8
  use_injection: [True, False]
  pretrained: /share/models/rtformer_slim_backbone_imagenet_pretrained.pdparams

```

# 报错信息
转paddle  inference后， Nvidia上运行正常，XPU上运行报错， 报错信息如下：
```python
 module.model.run()
RuntimeError: (PreconditionNotMet) No transform is applied for the data needs to be transformed.
  [Hint: Expected transformed == true, but received transformed:0 != true:1.] (at /share/xpu-kunlun/build/Paddle/paddle/fluid/framework/data_transform.cc:127)
  [operator < bilinear_interp_v2 > error]
```
