### ISSUE TITLE
4080训练，经常意外中断

### ISSUE THREAD

**Issue by hhh151671** [PaddlePaddle/Paddle#54203]
### bug描述 Describe the Bug

配置信息：
GPU: 4080
cuda11.3
cudnn8.9
驱动：530.41.03 
paddle：2.4.2

在2080TI上训练PPMatting，可以正常训练；但同样参数换到4080上，经常会因为各种问题导致训练中断：
1.直接卡住，而且显存占用接近14/16G，显存占比却是0
2.
```
  File "/home/cv/anaconda3/envs/py10/lib/python3.10/site-packages/paddle/optimizer/optimizer.py", line 754, in _add_accumulator
    var_name in self._accumulators_holder
AssertionError: Optimizer set error, batch_norm2d_177.b_0_velocity_1 should in state dict
```
3.
```
  File "/home/cv/anaconda3/envs/py10/lib/python3.10/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 297, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
OSError: (External) CUDNN error(4), CUDNN_STATUS_INTERNAL_ERROR.
  [Hint: Please search for the error code(4) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/phi/kernels/gpudnn/conv_grad_kernel.cu:583)

```
4.
```

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1685437112 (unix time) try "date -d @1685437112" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 3633 (TID 0x7fb6c2a49280) from PID 0 ***]

```
5. ...

**Comment by zyfncg** [comment]
从2080TI换到4080，除了显卡其他环境配置都是一样的吗？

**Comment by hhh151671** [comment]
> 从2080TI换到4080，除了显卡其他环境配置都是一样的吗？

只有驱动不一样530.41.03，4080是 2080Ti是 465.19.01 ；
剩下的cuda，cudnn版本都是一样的，训练的配置文件也是一样的

**Comment by zyfncg** [comment]
是使用的docker容器吗？

**Comment by hhh151671** [comment]
> 是使用的docker容器吗？

不是，是在ubuntu22.04桌面端跑的

**Comment by zyfncg** [comment]
好的，可以提供下能复现问题的训练脚本吗？

**Comment by hhh151671** [comment]
> 好的，可以提供下能复现问题的训练脚本吗？

训练脚本：
```bash
WORK_DIR=$(cd $(dirname $0); pwd)

cd ..
python label/update_txt_paths.py \
--data_dir ${WORK_DIR}/data

cd /home/cv/workstation/FrameM/PaddleSeg/Matting

config=${WORK_DIR}/ppmatting-hrnet_w48-distinctions.yml
output=${WORK_DIR}/output

python -u tools/train.py \
--config ${config} \
--do_eval  \
--use_vdl  \
--save_interval 500  \
--save_dir ${output}   \
--num_workers 0 \
--resume_model  ${output}/iter_6500/
```

配置文件：yaml
```
batch_size: 2
iters: 300000

train_dataset:
  type: MattingDataset
  dataset_root: /home/cv/workstation/segscripts/board_seg/data
  train_file: train.txt
  transforms:
    - type: LoadImages
    - type: Padding
      target_size: [512, 512]
    - type: RandomCrop
      crop_size: [[512, 512],[640, 640], [800, 800]]
    - type: Resize
      target_size: [512, 512]
    # - type: Resize
    #   target_size: [800, 800]
    - type: RandomDistort
    - type: RandomBlur
      prob: 0.1
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: Normalize
  mode: train
  separator: '|'

val_dataset:
  type: MattingDataset
  dataset_root: /home/cv/workstation/segscripts/board_seg/data
  val_file: val.txt
  transforms:
    - type: LoadImages
    - type: LimitShort
      max_short: 1536
    # - type: Resize
    #   target_size: [800, 800]

    - type: ResizeToIntMult
      mult_int: 32
    - type: Normalize
  mode: val
  get_trimap: False
  separator: '|'

model:
  type: PPMatting
  backbone:
    type: HRNet_W48
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
  pretrained: Null

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.005
  # learning_rate: 0.001
  end_lr: 0
  power: 0.9
```
